In [ ]:
Read Data from JSON
In [ ]:
fd = open("record.json",'r')
r = fd.read()
fd.close()

record = json.loads(r)
In [ ]:
record
Out[ ]:
{'1001': {'name': 'Choco Cake', 'pr': 100, 'qn': 34},
 '1002': {'name': 'Milk Cake', 'pr': 800, 'qn': 100},
 '1003': {'name': 'Drink', 'pr': 85, 'qn': 100},
 '1004': {'name': 'Candy', 'pr': 5, 'qn': 1000},
 '1005': {'name': 'Pen', 'pr': 20, 'qn': 100},
 '1006': {'name': 'Phone', 'pr': 50000, 'qn': 10},
 '1007': {'name': 'Mic', 'pr': 1500, 'qn': 0},
 '1008': {'name': 'Case', 'pr': 599, 'qn': 5}
 '1009': {'name': 'Choco ', 'pr': 100, 'qn': 34},
 '1010': {'name': 'Milk ', 'pr': 800, 'qn': 100},
 '1011': {'name': 'Drinking water', 'pr': 85, 'qn': 100},
 '1012': {'name': 'Mango Candy', 'pr': 50, 'qn': 100},
 '1013': {'name': 'Pencil', 'pr': 20, 'qn': 1001},
 '1014': {'name': 'Phonebook', 'pr': 5000, 'qn': 10},
 '1015': {'name': 'Mango', 'pr': 1500, 'qn': 0},
 '1016': {'name': 'Cream package', 'pr': 599, 'qn': 5},
 '1017': {'name': 'Banana', 'pr': 80, 'qn': 10},
 '1018': {'name': 'Guava', 'pr': 85, 'qn': 100},
 '1019': {'name': 'Orange Candy', 'pr': 50, 'qn': 101},
 '1020': {'name': 'Highlighter', 'pr': 201, 'qn': 1000},
 '1021': {'name': 'iPhone', 'pr': 5000, 'qn': 100},
 '1022': {'name': 'Microprocessor', 'pr': 1500, 'qn': 1},
 '1023': {'name': 'Red Colour', 'pr': 599, 'qn': 5}
 '1024': {'name': 'Notebook', 'pr': 800, 'qn': 1002},
 '1025': {'name': 'Mouse', 'pr': 85, 'qn': 1001},
 '1026': {'name': 'Computer', 'pr': 50, 'qn': 100},
 '1027': {'name': 'Red pen', 'pr': 200, 'qn': 100},
 '1028': {'name': 'Gallery', 'pr': 5000, 'qn': 100},
 '1029': {'name': 'Orange', 'pr': 150, 'qn': 0},
 '1030': {'name': 'Cashew', 'pr': 5990, 'qn': 4}}}
Add New Item into Inventory
In [ ]:
prod_id = str(input("Enter product id:"))
name = str(input("Enter name:"))
pr = int(input("Enter price:"))
qn = int(input("Enter quantity:"))

record[prod_id] = {'name': name, 'pr': pr, 'qn': qn}

js = json.dumps(record)

fd = open("record.json",'w')
fd.write(js)
fd.close()
Enter product id:1009
Enter name:Keyboard
Enter price:1999
Enter quantity:10
In [ ]:
record
Out[ ]:
{'1001': {'name': 'Choco Cake', 'pr': 100, 'qn': 34},
 '1002': {'name': 'Milk Cake', 'pr': 800, 'qn': 100},
 '1003': {'name': 'Drink', 'pr': 85, 'qn': 100},
 '1004': {'name': 'Candy', 'pr': 5, 'qn': 1000},
 '1005': {'name': 'Pen', 'pr': 20, 'qn': 100},
 '1006': {'name': 'Phone', 'pr': 50000, 'qn': 10},
 '1007': {'name': 'Mic', 'pr': 1500, 'qn': 0},
 '1008': {'name': 'Case', 'pr': 599, 'qn': 5},
 '1009': {'name': 'Keyboard', 'pr': 1999, 'qn': 10}}
In [ ]:
del record['1001']
In [ ]:
record
Out[ ]:
{'1002': {'name': 'Milk Cake', 'pr': 800, 'qn': 100},
 '1003': {'name': 'Drink', 'pr': 85, 'qn': 100},
 '1004': {'name': 'Candy', 'pr': 5, 'qn': 1000},
 '1005': {'name': 'Pen', 'pr': 20, 'qn': 100},
 '1006': {'name': 'Phone', 'pr': 50000, 'qn': 10},
 '1007': {'name': 'Mic', 'pr': 1500, 'qn': 0},
 '1008': {'name': 'Case', 'pr': 599, 'qn': 5},
 '1009': {'name': 'Keyboard', 'pr': 1999, 'qn': 10}}